x-kafka-environment: &kafka-environment
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093,2@kafka2:9093,3@kafka3:9093"

services:
  kafka:
    image: bitnami/kafka:${DIP_INFRA_KAFKA_IMAGE_TAG}
    environment:
      <<: *kafka-environment
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_EXTERNAL_HOST}:9094
    volumes:
      - kafka1:/bitnami/kafka
    ports:
      - 9092
      - 9093
      - 9094

  kafka2:
    image: bitnami/kafka:${DIP_INFRA_KAFKA_IMAGE_TAG}
    environment:
      <<: *kafka-environment
      KAFKA_CFG_NODE_ID: "2"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,EXTERNAL://${KAFKA2_EXTERNAL_HOST}:9094
    volumes:
      - kafka2:/bitnami/kafka
    ports:
      - 9092
      - 9093
      - 9094

  kafka3:
    image: bitnami/kafka:${DIP_INFRA_KAFKA_IMAGE_TAG}
    environment:
      <<: *kafka-environment
      KAFKA_CFG_NODE_ID: "3"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,EXTERNAL://${KAFKA3_EXTERNAL_HOST}:9094
    volumes:
      - kafka3:/bitnami/kafka
    ports:
      - 9092
      - 9093
      - 9094

volumes:
  kafka1:
  kafka2:
  kafka3:

networks:
  default:
    name: ${DIP_INFRA_NETWORK_NAME}
    external: true
