services:
  zookeeper:
    image: bitnami/zookeeper:${DIP_INFRA_ZOOKEEPER_IMAGE_TAG}
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper:/bitnami
    ports:
      - 2181

  kafka:
    image: bitnami/kafka:${DIP_INFRA_KAFKA_IMAGE_TAG}
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ENABLE_KRAFT: "no"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - kafka:/data
    ports:
      - 9092
      - 9094

volumes:
  zookeeper:
  kafka:

networks:
  default:
    name: ${DIP_INFRA_NETWORK_NAME}
    external: true
